### ISSUE TITLE
cookie如何获取

### ISSUE THREAD

**Issue by cxc00123** [jackwd387/FQToolBox#2]
如题，希望大佬详细教学一下番茄小说如何获取cookie

**Comment by jackwd387** [comment]
电脑:
1.登陆https://fanqienovel.com/
2.打开devtools
3.点击书架
4.如图所示获取cookie
![cookie_get](https://github.com/user-attachments/assets/a8531fa8-8e9f-4468-975f-f2ddc214c19e)

**Comment by cxc00123** [comment]
![Screenshot_2024-12-04-21-17-01-09_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/c1d31cc1-7446-455c-92c9-0713c7ccc6e8)

使用termux安装python运行报错
